### NOTE: To use this file VSC REST Client extension must be installed 

### Finds all Accounts
GET http://localhost:3000/accounts

### Finds an Account by id
GET http://localhost:3000/accounts/39400a39-d402-4551-895a-a66a2dacb72f

### Creates an Account
POST http://localhost:3000/accounts
Content-Type: application/json

{
    "firstName": "Marc",
    "lastName": "Laurin",
    "email": "marc@example.com",
    "password": "1234"
}