### NOTE: To use this file VSC REST Client extension must be installed 

### Finds all Genres
GET http://localhost:3000/genres

### Finds a Genre by id
GET http://localhost:3000/genres/dd24a9bf-5c42-4140-a7cd-6f3a2410a654

### Creates a Genre
POST http://localhost:3000/genres
Content-Type: application/json

{
    "createTranslationPayloads": [
        {
            "languageId": "4d68f0b4-c87b-43e2-8ba1-78fb4d0d3302",
            "text": "Comedy"
        },
        {
            "languageId": "be277c64-a1e4-4aa1-b8da-e90df53a9890",
            "text": "Comedia"
        }
    ]
}

### Updates a Genre
PUT http://localhost:3000/genres/dd24a9bf-5c42-4140-a7cd-6f3a2410a654
Content-Type: application/json

{
    "updateTranslationPayloads": [
        {
            "languageId": "4d68f0b4-c87b-43e2-8ba1-78fb4d0d3302",
            "text": "Drama"
        },
        {
            "languageId": "be277c64-a1e4-4aa1-b8da-e90df53a9890",
            "text": "Drama"
        }
    ]
}

### Deletes a Genre
DELETE http://localhost:3000/genres/dd24a9bf-5c42-4140-a7cd-6f3a2410a654