### NOTE: To use this file VSC REST Client extension must be installed 

### Finds all Genres
GET http://localhost:3000/genres

### Finds a Genre by id
GET http://localhost:3000/genres/f632b005-633a-4152-adf1-924683818a7a

### Creates a Genre
POST http://localhost:3000/genres
Content-Type: application/json

{
    "createTranslationPayloads": [
        {
            "languageCode": "en",
            "text": "Suspense"
        },
        {
            "languageCode": "es",
            "text": "Suspensio"
        }
    ]
}

### Updates a Genre
PUT http://localhost:3000/genres/a019291c-fcc1-4436-91bd-b38be4d16c02
Content-Type: application/json

{
    "updateTranslationPayloads": [
        {
            "languageCode": "en",
            "text": "Drama"
        },
        {
            "languageCode": "es",
            "text": "Drama"
        }
    ]
}

### Deletes a Genre
DELETE http://localhost:3000/genres/d8f75b6f-1f2d-47cf-a0d2-5125a81d3160