### NOTE: To use this file VSC REST Client extension must be installed 

### Finds all Genres
GET http://localhost:3000/genres

### Finds a Genre by id
GET http://localhost:3000/genres/65282964-4687-4aa7-bc42-80ed84aaa597

### Creates a Genre
POST http://localhost:3000/genres
Content-Type: application/json

{
    "createTranslationPayloads": [
        {
            "languageId": "e401938c-a390-4cf0-9eac-7379f7735711",
            "text": "Comedy"
        },
        {
            "languageId": "be277c64-a1e4-4aa1-b8da-e90df53a9890",
            "text": "Comedia"
        }
    ]
}

### Updates a Genre
PUT http://localhost:3000/genres/7529b627-789a-4353-a671-b079a68f3d79
Content-Type: application/json

{
    "updateTranslationPayloads": [
        {
            "languageId": "e401938c-a390-4cf0-9eac-7379f7735711",
            "text": "Comedy"
        }
    ]
}

### Deletes a Genre
DELETE http://localhost:3000/genres/dd24a9bf-5c42-4140-a7cd-6f3a2410a654