### NOTE: To use this file VSC REST Client extension must be installed 

### Finds all Languages
GET http://localhost:3000/languages

### Finds a Language by id
GET http://localhost:3000/languages/4d68f0b4-c87b-43e2-8ba1-78fb4d0d3302

### Creates a Language
POST http://localhost:3000/languages
Content-Type: application/json

{
    "code": "es",
    "createTranslationPayloads": [
        {
            "languageId": "2028403e-1fec-464b-ac97-92985963f91f",
            "text": "French"
        },
        {
            "languageId": "f4cce80d-13db-42ee-9583-ebcd75b9d982",
            "text": "Frances"
        }
    ]
}

### Updates a Language
PUT http://localhost:3000/languages/be277c64-a1e4-4aa1-b8da-e90df53a9890
Content-Type: application/json

{
    "code": "es",
    "updateTranslationPayloads": [
        {
            "languageId": "972af4a6-84cd-474d-a159-08436daf1e43",
            "text": "Espagnol"
        },
        {
            "languageId": "4d68f0b4-c87b-43e2-8ba1-78fb4d0d3302",
            "text": "Spanish"
        },
        {
            "languageId": "be277c64-a1e4-4aa1-b8da-e90df53a9890",
            "text": "Espanol"
        }
    ]
}


### Deletes a Language
DELETE http://localhost:3000/languages/4d68f0b4-c87b-43e2-8ba1-78fb4d0d3302