### NOTE: To use this file VSC REST Client extension must be installed 

### Finds all Languages
GET http://localhost:3000/languages

### Finds a Language by id
GET http://localhost:3000/languages/972af4a6-84cd-474d-a159-08436daf1e43

### Creates a Language
POST http://localhost:3000/languages
Content-Type: application/json

{
    "code": "de",
    "createLabelTranslationPayloads": [
        {
            "languageId": "972af4a6-84cd-474d-a159-08436daf1e43",
            "text": "Allemand"
        },
        {
            "languageId": "e401938c-a390-4cf0-9eac-7379f7735711",
            "text": "German"
        },
        {
            "languageId": "be277c64-a1e4-4aa1-b8da-e90df53a9890",
            "text": "Aleman"
        }
    ]
}

### Updates a Language
PUT http://localhost:3000/languages/be277c64-a1e4-4aa1-b8da-e90df53a9890
Content-Type: application/json

{
    "code": "es",
    "updateLabelTranslationPayloads": [
        {
            "languageId": "972af4a6-84cd-474d-a159-08436daf1e43",
            "text": "Espagnol"
        },
        {
            "languageId": "e401938c-a390-4cf0-9eac-7379f7735711",
            "text": "Spanish"
        },
        {
            "languageId": "be277c64-a1e4-4aa1-b8da-e90df53a9890",
            "text": "Espanol"
        }
    ]
}


### Deletes a Language
DELETE http://localhost:3000/languages/ee1228b9-277b-4e90-8557-698f89ce0f38