Parameters:
  Env:
    Description: Environment
    Type: String

  AppName:
    Description: 'App name'
    Type: String

  VpcId:
    Description: 'Vpc ID'
    Type: String

  PrivateAppSubnetAId:
    Description: 'Private app subnet A ID'
    Type: String

  PrivateAppSubnetBId:
    Description: 'Private app subnet B ID'
    Type: String

  Ec2InstanceAId:
    Description: 'Ec2 instance A ID'
    Type: String

  Ec2InstanceBId:
    Description: 'Ec2 instance A ID'
    Type: String

  ApplicationLoadBalancerSecurityGroupId:
    Description: 'Application load balancer security group ID'
    Type: String

Mappings:
  EnvMap:
    dev:
      Port: 80
      Protocol: HTTP

    prod:
      Port: 443
      Protocol: HTTPS

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${AppName}-alb-${Env}'
      Scheme: internet-facing
      # NOTE: At least two subnets in two different Availability Zones must be specified
      Subnets:
        - !Ref PrivateAppSubnetAId
        - !Ref PrivateAppSubnetBId
      SecurityGroups:
        - !Ref ApplicationLoadBalancerSecurityGroupId
      Tags:
        - Key : Name
          Value: !Sub '${AppName}-alb-${Env}'

  ApplicationLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Name: !Sub '${AppName}-alb-tg-${Env}'
      Port: !FindInMap [EnvMap, !Ref Env, Port]
      Protocol: !FindInMap [EnvMap, !Ref Env, Protocol]
      ProtocolVersion: HTTP1
      IpAddressType: ipv4
      HealthCheckPath: '/app/health'
      HealthCheckIntervalSeconds: 60
      HealthyThresholdCount: 2
      TargetType: instance
      Targets:
        - Id: !Ref Ec2InstanceAId
          Port: !FindInMap [EnvMap, !Ref Env, Port]

        - Id: !Ref Ec2InstanceBId
          Port: !FindInMap [EnvMap, !Ref Env, Port]
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
      Tags:
        - Key : Name
          Value: !Sub '${AppName}-alb-tg-${Env}'

  ApplicationLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - ApplicationLoadBalancer
      - ApplicationLoadBalancerTargetGroup
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: !FindInMap [EnvMap, !Ref Env, Port]
      Protocol: !FindInMap [EnvMap, !Ref Env, Protocol]
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ApplicationLoadBalancerTargetGroup

Outputs:
  ApplicationLoadBalancerDnsName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName