### NOTE: To use this file VSC REST Client extension must be installed 

### Finds all Plans
GET http://localhost:3000/plans
Authorization: Bearer accessToken

### Finds a Plan by id
GET http://localhost:3000/plans/8d1dc821-3ebe-4aad-8238-e7fdfea5fbba
Authorization: Bearer accessToken

### Creates a Plan
POST http://localhost:3000/plans
Authorization: Bearer accessToken
Content-Type: application/json

{
    "price": 14.50,
    "createLabelTranslationPayloads": [
        {
            "languageId": "e401938c-a390-4cf0-9eac-7379f7735711",
            "text": "Elite Plan",
        },
         {
            "languageId": "972af4a6-84cd-474d-a159-08436daf1e43",
            "text": "Plan Elite",
        }
    ],
    "createDescriptionTranslationPayloads": [
        {
            "languageId": "e401938c-a390-4cf0-9eac-7379f7735711",
            "text": "Elite Plan description",
        },
         {
            "languageId": "972af4a6-84cd-474d-a159-08436daf1e43",
            "text": "description Plan Elite",
        }
    ]
}