### NOTE: To use this file VSC REST Client extension must be installed 

### Finds all Plans
GET http://localhost:3000/plans
Authorization: Bearer accessToken

### Finds a Plan by id
GET http://localhost:3000/plans/b1bbf6d6-ac22-49c4-b64b-cd2ed524e948
Authorization: Bearer accessToken

### Creates a Plan
POST http://localhost:3000/plans
Authorization: Bearer accessToken
Content-Type: application/json

{
    "name": "Elite Plan",
    "description": "Familial plan description",
    "price": 16.50
}