Parameters:
  Env:
    Description: Environment
    Type: String

  AppName:
    Description: 'App name'
    Type: String

Conditions:
  IsProd: !Equals [!Ref Env, prod]

Resources:
  TranscodedVideosS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-transcoded-videos-${Env}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - Id: !Sub '${AppName}-transcoded-videos-cors-rule-${Env}'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - HEAD
              - POST
              - PUT
            AllowedOrigins:
              !If [
                IsProd,
                # If IsProd
                ['*'],
                # Else
                ['*']
              ]
            ExposedHeaders:
              - Connection
              - Server
              - Date
            MaxAge: 3600

Outputs:
  TranscodedVideosS3BucketId:
    Value: !Ref TranscodedVideosS3Bucket

  TranscodedVideosS3BucketArn:
    Value: !GetAtt TranscodedVideosS3Bucket.Arn

  TranscodedVideosS3BucketRegionalDomainName:
    Value: !GetAtt TranscodedVideosS3Bucket.RegionalDomainName