### NOTE: To use this file VSC REST Client extension must be installed 

### Finds all Accounts
GET http://localhost:3000/accounts

### Finds an Account by id
GET http://localhost:3000/accounts/account-id-goes-here