Parameters:
  Env:
    Description: Environment
    Type: String
    AllowedValues:
      - dev
      - prod

  AppName:
    Description: 'App name'
    Type: String

  Ec2InstanceType:
    Description: 'Type of EC2 instance'
    Type: String
    AllowedValues:
      - t2.micro

  Ec2InstanceAmiId:
    Description: 'Id of Amazon Machine Image (AMI)'
    Type: String
    AllowedValues:
      - ami-0c4596ce1e7ae3e68

  Ec2InstanceRootVolumeType:
    Description: 'Type of EC2 instance root volume'
    Type: String
    AllowedValues:
      - gp2

  Ec2InstanceRootVolumeSize:
    Description: 'Size in GB of EC2 instance root volume'
    Type: String
    AllowedValues:
      - 30

  RdsInstanceType:
    Description: 'RDS instance type'
    Type: String
    AllowedValues:
      - db.t3.micro

  RdsInstanceEngine:
    Description: 'RDS instance database'
    Type: String
    AllowedValues:
      - postgres

  RdsInstanceEngineVersion:
    Description: 'RDS instance database version'
    Type: String
    AllowedValues:
      - 15.6

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AppName}-cloudformation.s3.${AWS::Region}.amazonaws.com/s3/s3-stack.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName

  CloudfrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AppName}-cloudformation.s3.${AWS::Region}.amazonaws.com/cloudfront/cloudfront-stack.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        TranscodedVideosS3BucketRegionalDomainName: !GetAtt S3Stack.Outputs.TranscodedVideosS3BucketRegionalDomainName

  PolicyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AppName}-cloudformation.s3.${AWS::Region}.amazonaws.com/policy/policy-stack.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        TranscodedVideosS3BucketId: !GetAtt S3Stack.Outputs.TranscodedVideosS3BucketId
        TranscodedVideosS3BucketArn: !GetAtt S3Stack.Outputs.TranscodedVideosS3BucketArn
        TranscodedVideosCloudfrontDistributionId: !GetAtt CloudfrontStack.Outputs.TranscodedVideosCloudfrontDistributionId

  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AppName}-cloudformation.s3.${AWS::Region}.amazonaws.com/vpc/vpc-stack.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName

  SgStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AppName}-cloudformation.s3.${AWS::Region}.amazonaws.com/sg/sg-stack.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        VpcId: !GetAtt VpcStack.Outputs.VpcId

  Ec2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AppName}-cloudformation.s3.${AWS::Region}.amazonaws.com/ec2/ec2-stack.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        PrivateAppSubnetAId: !GetAtt VpcStack.Outputs.PrivateAppSubnetAId
        PrivateAppSubnetBId: !GetAtt VpcStack.Outputs.PrivateAppSubnetBId
        RdsInstanceSecurityGroupId: !GetAtt SgStack.Outputs.RdsInstanceSecurityGroupId
        Ec2InstanceSecurityGroupId: !GetAtt SgStack.Outputs.Ec2InstanceSecurityGroupId
        Ec2InstanceConnectEndpointSecurityGroupId: !GetAtt SgStack.Outputs.Ec2InstanceConnectEndpointSecurityGroupId
        Ec2InstanceType: !Ref Ec2InstanceType
        Ec2InstanceAmiId: !Ref Ec2InstanceAmiId
        Ec2InstanceRootVolumeType: !Ref Ec2InstanceRootVolumeType
        Ec2InstanceRootVolumeSize: !Ref Ec2InstanceRootVolumeSize

  AlbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AppName}-cloudformation.s3.${AWS::Region}.amazonaws.com/alb/alb-stack.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PrivateAppSubnetAId: !GetAtt VpcStack.Outputs.PrivateAppSubnetAId
        PrivateAppSubnetBId: !GetAtt VpcStack.Outputs.PrivateAppSubnetBId
        Ec2InstanceAId: !GetAtt Ec2Stack.Outputs.Ec2InstanceAId
        Ec2InstanceBId: !GetAtt Ec2Stack.Outputs.Ec2InstanceBId
        ApplicationLoadBalancerSecurityGroupId: !GetAtt SgStack.Outputs.ApplicationLoadBalancerSecurityGroupId

  RdsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${AppName}-cloudformation.s3.${AWS::Region}.amazonaws.com/rds/rds-stack.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        PrivateDataSubnetAId: !GetAtt VpcStack.Outputs.PrivateDataSubnetAId
        PrivateDataSubnetBId: !GetAtt VpcStack.Outputs.PrivateDataSubnetBId
        RdsInstanceSecurityGroupId: !GetAtt SgStack.Outputs.RdsInstanceSecurityGroupId
        RdsInstanceType: !Ref RdsInstanceType
        RdsInstanceEngine: !Ref RdsInstanceEngine
        RdsInstanceEngineVersion: !Ref RdsInstanceEngineVersion


Outputs:
  CloudfrontUrl:
     Value: !Join ['', ['https://', !GetAtt CloudfrontStack.Outputs.TranscodedVideosCloudfrontDistributionDomainName]]

  ApplicationLoadBalancerUrl:
    Value: !Join ['', ['http://', !GetAtt AlbStack.Outputs.ApplicationLoadBalancerDnsName]]