Parameters:
  Env:
    Description: Environment
    Type: String

  AppName:
    Description: 'App name'
    Type: String

  VpcId:
    Description: 'Vpc ID'
    Type: String

  PrivateAppSubnetId:
    Description: 'Private app subnet ID'
    Type: String

  Ec2InstanceType:
    Description: 'Type of EC2 instance'
    Type: String

  Ec2InstanceAmiId:
    Description: 'ID of Amazon Machine Image (AMI)'
    Type: String

Resources:
  Ec2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupName: !Sub '${AppName}-ec2-sg-${Env}'
      GroupDescription: 'Security group for ${AppName} ${Env} ec2 instance'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp:  0.0.0.0/0
        # NOTE: RDP (remote windows) connection
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp:  0.0.0.0/0
        # NOTE: HTTPS connection
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp:  0.0.0.0/0
        # NOTE: HTTP connection
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp:  0.0.0.0/0
        # NOTE: SSH (remote linux) or SFTP connection
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:  0.0.0.0/0
        # NOTE: FTP connection
        - IpProtocol: tcp
          FromPort: 21
          ToPort: 21
          CidrIp:  0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-ec2-sg-${Env}'

  # NOTE: When you create a new key pair using AWS CloudFormation, the private key is saved to AWS Systems Manager Parameter Store
  # NOTE: /ec2/keypair/key_pair_id
  Ec2InstanceKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyFormat: pem
      KeyType: rsa
      KeyName: !Sub '${AppName}-ec2-kp-${Env}'

  Ec2Instance:
    Type: AWS::EC2::Instance
    DependsOn:
      - Ec2InstanceSecurityGroup
      - Ec2InstanceKeyPair
    Properties:
      # NOTE: Ubuntu Server 24.04 LTS (HVM), SSD Volume Type (Free tier eligible)
      ImageId: !Ref Ec2InstanceAmiId
      SubnetId: !Ref PrivateAppSubnetId
      # NOTE: The key used to access the instance
      # NOTE: If you do not specify a key pair, you can't connect to the instance unless you choose an AMI that is configured to allow users another way to log in
      KeyName: !Ref Ec2InstanceKeyPair
      # NOTE: Eligible free tier
      InstanceType: !Ref Ec2InstanceType
      SecurityGroupIds:
        - !Ref Ec2InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # good practice to update existing packages
          sudo apt-get update -y
          sudo apt install -y golang-go
          sudo apt install -y git-all
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-ec2-${Env}'

  Ec2InstanceElasticIp:
    Type: AWS::EC2::EIP
    DependsOn:
      - Ec2Instance
    Properties:
      InstanceId: !Ref Ec2Instance
      Domain: vpc