Parameters:
  Env:
    Description: Environment
    Type: String

  AppName:
    Description: 'App name'
    Type: String

  PrivateAppSubnetAId:
    Description: 'Private app subnet A ID'
    Type: String

  PrivateAppSubnetBId:
    Description: 'Private app subnet B ID'
    Type: String

  RdsInstanceSecurityGroupId:
    Description: 'EC2 instance security group ID'
    Type: String

  Ec2InstanceSecurityGroupId:
    Description: 'EC2 instance security group ID'
    Type: String

  Ec2InstanceConnectEndpointSecurityGroupId:
    Description: 'EC2 instance connect endpoint security group ID'
    Type: String

  Ec2InstanceType:
    Description: 'Type of EC2 instance'
    Type: String

  Ec2InstanceAmiId:
    Description: 'ID of Amazon Machine Image (AMI)'
    Type: String

  Ec2InstanceRootVolumeType:
    Description: 'Type of EC2 instance root volume'
    Type: String

  Ec2InstanceRootVolumeSize:
    Description: 'Size of EC2 instance root volume'
    Type: String

Resources:
  # EC2 INSTANCE A
  Ec2InstanceConnectEndpointA:
    Type: AWS::EC2::InstanceConnectEndpoint
    Properties:
      PreserveClientIp: false
      SecurityGroupIds: 
        - !Ref Ec2InstanceConnectEndpointSecurityGroupId
      SubnetId: !Ref PrivateAppSubnetAId
      Tags: 
        - Key: Name
          Value: !Sub '${AppName}-ec2-eice-${AWS::Region}a-${Env}'

  # NOTE: When you create a new key pair using AWS CloudFormation, the private key is saved to AWS Systems Manager Parameter Store
  # NOTE: /ec2/keypair/key_pair_id
  Ec2InstanceKeyPairA:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyFormat: pem
      KeyType: rsa
      KeyName: !Sub '${AppName}-ec2-kp-${AWS::Region}a-${Env}'

  Ec2InstanceA:
    Type: AWS::EC2::Instance
    DependsOn:
      - Ec2InstanceKeyPairA
    Properties:
      # NOTE: Ubuntu Server 24.04 LTS (HVM), SSD Volume Type (Free tier eligible)
      ImageId: !Ref Ec2InstanceAmiId
      SubnetId: !Ref PrivateAppSubnetAId
      # NOTE: The key used to access the instance
      # NOTE: If you do not specify a key pair, you can't connect to the instance unless you choose an AMI that is configured to allow users another way to log in
      KeyName: !Ref Ec2InstanceKeyPairA
      # NOTE: Eligible free tier
      InstanceType: !Ref Ec2InstanceType
      # NOTE: Root volume
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            DeleteOnTermination: true
            # NOTE: Size is in GB
            VolumeSize: !Ref Ec2InstanceRootVolumeSize
            VolumeType: !Ref Ec2InstanceRootVolumeType
      SecurityGroupIds:
        - !Ref Ec2InstanceSecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # good practice to update existing packages
          sudo apt-get update -y
          sudo apt install -y golang-go
          sudo apt install -y git-all
          sudo apt install -y ffmpeg
          sudo apt install -y postgresql
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-ec2-${AWS::Region}a-${Env}'

  # EC2 INSTANCE B
  # NOTE: When you create a new key pair using AWS CloudFormation, the private key is saved to AWS Systems Manager Parameter Store
  # NOTE: /ec2/keypair/key_pair_id
  Ec2InstanceKeyPairB:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyFormat: pem
      KeyType: rsa
      KeyName: !Sub '${AppName}-ec2-kp-${AWS::Region}b-${Env}'

  Ec2InstanceB:
    Type: AWS::EC2::Instance
    DependsOn:
      - Ec2InstanceKeyPairB
    Properties:
      # NOTE: Ubuntu Server 24.04 LTS (HVM), SSD Volume Type (Free tier eligible)
      ImageId: !Ref Ec2InstanceAmiId
      SubnetId: !Ref PrivateAppSubnetBId
      # NOTE: The key used to access the instance
      # NOTE: If you do not specify a key pair, you can't connect to the instance unless you choose an AMI that is configured to allow users another way to log in
      KeyName: !Ref Ec2InstanceKeyPairB
      # NOTE: Eligible free tier
      InstanceType: !Ref Ec2InstanceType
      # NOTE: Root volume
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            DeleteOnTermination: true
            # NOTE: Size is in GB
            VolumeSize: !Ref Ec2InstanceRootVolumeSize
            VolumeType: !Ref Ec2InstanceRootVolumeType
      SecurityGroupIds:
        - !Ref Ec2InstanceSecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          # good practice to update existing packages
          sudo apt-get update -y
          sudo apt install -y golang-go
          sudo apt install -y git-all
          sudo apt install -y ffmpeg
          sudo apt install -y postgresql
      Tags:
        - Key: Name
          Value: !Sub '${AppName}-ec2-${AWS::Region}b-${Env}'

Outputs:
  Ec2InstanceAId:
    Value: !Ref Ec2InstanceA

  Ec2InstanceBId:
    Value: !Ref Ec2InstanceB