### NOTE: To use this file VSC REST Client extension must be installed 

### Logs in
POST http://localhost:3000/authentication/login
Content-Type: application/json

{
    "email": "marc@example.com",
    "password": "1234"
}