### NOTE: To use this file VSC REST Client extension must be installed 

### Logs in
POST http://localhost:3000/authentication/login
Content-Type: application/json

{
    "email": "marc@example.com",
    "password": "1234"
}

### Registers
POST http://localhost:3000/authentication/register
Content-Type: application/json

{
    "firstName": "Marc",
    "lastName": "Laurin",
    "email": "marc2@example.com",
    "password": "1234",
    "planId": "92885497-d1cd-4407-834a-141ee7ae1083"
}